article/urls.py
from django.urls import path
from . import views

app_name = 'article'
# urls
urlpatterns = [
    path('article_list/', views.article_list, name='article_list'),
    path('article/<int:id>/', views.article_page, name='article_page'),
    path('add/', views.article_add, name='article_add'),
    path('artikel/<int:id>/delete/', views.article_delete, name='article_delete'),
    path('data_article', views.data_article, name='data_article'),
]

komentar/urls.py
from django.urls import path
from . import views

app_name = 'komentar'
urlpatterns = [
    path('add_comment/<int:id>/', views.add_comment, name='add_comment'),
    path('data_comment', views.data_comment, name='data_comment'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kasus', views.kasus),
]

ppwb01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('relawan.urls')),
    path('', include('article.urls')),
    path('', include('komentar.urls')),
    path('', include('account.urls')),
]

article/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Article(models.Model):
    artikel = models.CharField(max_length=50, help_text='Nama Artikel')
    penulis = models.CharField(max_length=50, help_text='Nama Penulis')
    deskripsi = models.TextField(help_text='Deskripsi')
    tanggal_penulisan = models.DateTimeField(default=timezone.now,help_text='Tanggal Penulisan')
    def __str__(self):
        return "{} | {} | {} | {}".format(self.artikel, self.penulis, self.deskripsi, self.tanggal_penulisan)

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        # artikel = forms.CharField(label="Nama Artikel",max_length=50,widget=forms.TextInput(attrs={"placeholder":"","class":"form-control",}))
        # penulis = forms.CharField(label="Penulis Artikel",max_length=50,widget=forms.TextInput(attrs={"placeholder":"","class":"form-control",}))
        # deskripsi = forms.CharField(label="Deskripsi",widget=forms.TextInput(attrs={"placeholder":"Tulis Konten Artikel Anda","class":"form-control",}))
        model = Article
        fields = ['artikel', 'penulis', 'deskripsi']
        labels = {
            'artikel':'Nama Artikel',
            'penulis':'Penulis Artikel',
            'deskripsi':'Deskripsi',
        }
        widgets = {
            'artikel':forms.TextInput(attrs={
                'placeholder':'',
                'class':'form-control',
            }),
            'penulis': forms.TextInput(attrs = {
                'placeholder':'',
                'class':'form-control',
            }),
            'deskripsi':forms.TextInput(attrs={
                'placeholder':'Tulis Konten Artikel Anda Disini',
                'class':'form-control',
            }),
        
        }

article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

# Create your views here.
@login_required(login_url='/login')
def article_list(request):
    artikels = Article.objects.all()
    return render(request, 'article/landing.html', {'artikels':artikels})

def article_page(request, id):
    artikel = get_object_or_404(Article, id=id)

    response = {
        'artikel':artikel,
    }
    
    return render(request, 'article/view.html', response)

def article_add(request):
    data = {'success': False}
    artikels = Article()
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            artikel = form.save()
            artikel.save()
            return redirect('article:article_page', id=artikel.id)
    else:
        form = ArticleForm()
        artikel = Article.objects.all()
        context = {'form':form,'artikel':artikel}
        return render(request, 'article/form.html', context)

def article_delete(request, id):
    Article.objects.get(id=id).delete()
    return redirect('article:article_list')

def data_article(request):
    id_artikel = request.GET['q']
    artikel = Article.objects.get(id=id_artikel)

    dict_artikel = {
        'judul': artikel.artikel,
        'penulis': artikel.penulis,
        'deskripsi': artikel.deskripsi,
        'tanggal_penulisan': artikel.tanggal_penulisan
    }

    return JsonResponse(dict_artikel)

article/templates/article/form.html
{% extends 'base.html' %}
{% block content%}
<div class="dark">
    <h1>Artikel Baru</h1>
    <div class="container">
        <form method="POST" class="" id =>{% csrf_token %}
            {% for field in form %}
            <div class="container p-2">
                <label for="{{ field.name }}">{{ field.label }}</label>
                <div>
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <div class="row p-3">
                <div class="col-auto my-auto">
                    <button type="submit" class="btn btn-form">Simpan</button>
                </div>
                <div class="col-auto my-auto">
                    <a class="btn btn-danger" href="{% url 'article:article_list' %}">Batal</a>
                </div>
            </div>
            
        </form>
    </div>
</div>
{% endblock %}

article/templates/article/landing.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;700&display=swap" rel="stylesheet">
<link href="{% static 'css/TK2style.css' %}" rel="stylesheet">
{% endblock %}

{% block navcolor %}navbar-light{% endblock %}
{% block content %}
<div>
    <div class="container p-5">
        <h1>List Artikel</h1>
        
        <div class="container">
            <div class="row p-5">
                <div class="col"></div>
                <div class="col-auto">
                    <a class="btn btn-info" href="{% url 'article:article_add' %}">
                        Tambah Artikel
                    </a>
                </div>
                <div class="col"></div>
            </div>
            
            {% for artikel in artikels %}
            <div class="container p-3">
                <div class="row">
                    <div class="col">
                        <a href="{% url 'article:article_page' id=artikel.id %}"><h2>{{ artikel.artikel }}</h2></a>
                        <div class="container">
                            <p>Penulis: {{ artikel.penulis }}</p>
                            <p>Tanggal Penulisan: {{ artikel.tanggal_penulisan }}</p>
                        </div>
                    </div>
                    <div class="col-auto my-auto">
                        <a class="btn btn-danger" href="{% url 'article:article_delete' id=artikel.id %}">Hapus</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

article/templates/article/view.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<script src="{% static 'js/komentar/comment_js.js' %}"></script>
<script src="{% static 'js/artikel/artikel_js.js' %}"></script>
<script type="text/javascript">
    var id_artikel = '{{ artikel.id|escapejs }}';
    var url_submit = "{% url 'komentar:add_comment' id=artikel.id|escapejs %}"
</script>
{% endblock meta %}

{% block content%}
<div class="dark">
    <div class="container pt-5">
        <h1>{{ artikel.nama }}</h1>
        <div class="container p-5">
            <h3>Penulis: {{ artikel.penulis }}</h3>
            <h3>Tanggal Penulisan: {{ artikel.tanggal_penulisan }}</h3>
            <h3>Deskripsi:</h3> 
            <div class="container">
                <p>{{ artikel.deskripsi }}</p>
            </div>
            <div class="d-flex justify-content-center p-5">
                <a class="btn btn-info" href="{% url 'article:article_list' %}">Back</a>
            </div>
            <hr>
            <!-- bagian komentar mulai -->
            {% include 'komentar/komentar_form.html' %}

            <h3><span id="jumlah_komentar"></span> Komentar:</h3>
            <div id="comment_list">
            </div>
            <!-- bagian komentar selesai -->
        </div>
    </div>    
</div>
{% endblock %}