main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kasus', views.kasus),
]

ppwb01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('relawan.urls')),
    path('', include('article.urls')),
    path('', include('komentar.urls')),
    path('', include('account.urls')),
]

relawan/urls.py
from django.urls import re_path

from . import views

app_name = 'relawan'

urlpatterns = [
    re_path(r'^relawan', views.relawan, name='relawan'),
    re_path('formrelawan', views.formRelawan, name='formrelawan'),
    re_path('saverelawan', views.saverelawan, name='saverelawan'),
    re_path('dataKasus', views.dataKasus),
]

main/models.py
from django.db import models

# Create your models here.

relawan/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class RelawanList(models.Model):
    display_name = models.CharField(max_length=60)
    alamat = models.CharField(max_length=200)
    donasi = models.CharField(max_length=40)

# Create your models here.

relawan/forms.py
from django import forms
from .models import RelawanList

class Input_Form(forms.ModelForm):
	class Meta:
		model = RelawanList
		fields = ['display_name','alamat','donasi']
		error_messages = {
			'required' : 'Please Type'
		}
	input_attrs = {
		'type' : 'text',
		'placeholder' : 'Nama'
	}
	alamat_input = {
		'type' : 'text',
		'placeholder' : 'Alamat'
	}
	donasi_input = {
		'type' : 'text',
		'placeholder' : 'Jumlah Donasi'
	}

	display_name = forms.CharField(label='', required=True, max_length=60, widget=forms.TextInput(attrs=input_attrs))
	alamat = forms.CharField(label='', required=True, max_length=200, widget=forms.TextInput(attrs=alamat_input))
	donasi = forms.CharField(label='', required=True, max_length=40, widget=forms.TextInput(attrs=donasi_input))

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
import json
import requests

def home(request):
    response = requests.get('https://api.kawalcorona.com/indonesia/provinsi')
    data = response.json()
    kasus = []
    for o in data:
        datanya = {}
        datanya['provinsi'] = o['attributes']['Provinsi']
        datanya['kasus_positif'] = o['attributes']['Kasus_Posi']
        datanya['kasus_sembuh'] = o['attributes']['Kasus_Semb']
        datanya['kasus_meninggal'] = o['attributes']['Kasus_Meni']
        kasus.append(datanya)
    return render(request, 'main/home.html', {
        'data': kasus,
    })
    return JsonResponse(data)

def kasus(request):
    url = 'https://api.kawalcorona.com/indonesia/'
    ret = requests.get(url)
    data = json.loads(ret.content)
    print(data)
    return JsonResponse(data, safe=False)

relawan/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
import requests
import json
from .forms import Input_Form
from .models import RelawanList
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.forms.models import model_to_dict

# Create your views here.
@login_required(redirect_field_name='next', login_url='/login')
def relawan(request):
	relawans = RelawanList.objects.all()
	response = {'relawans' : relawans, 'input_form' : Input_Form}
	return render(request, 'main/relawan.html', response)

@login_required(login_url='/login')
def formRelawan(request):
	response = 	{'input_form' : Input_Form}
	return render(request, 'main/formRelawan.html', response)

def saverelawan(request):
	form = Input_Form()

	if request.is_ajax():
		form = Input_Form(request.POST)
		if form.is_valid():
				form.save()
				return JsonResponse({
					'message':'success'
					})
	return render(request,'main/relawan.html', {'form',form})

def dataKasus(request):
	relawans = RelawanList.objects.all().values()
	data = list(relawans)
	return JsonResponse(data, safe=False)

"""def newRelawan(request):
	form = Input_Form(request.POST)
	if request.method == 'POST':
		if form.is_valid():
				form.save()
				return HttpResponseRedirect('/relawan')
		else:
				return HttpResponseRedirect('/formrelawan')"""

relawan/templates/main/formRelawan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 5 Randa Mata Kuliah</title>
{% endblock meta %}

{% block content %}
  <section id="">
		<div class="container">
		<div class="card col-md-12">
			<h3>Silakan Masukan Data</h3><br>
			<form action="saverelawan" method="POST">
				{% csrf_token %}
				Nama: {{ input_form.display_name }}<br><br>
				Alamat: {{ input_form.alamat }}<br><br>
				Jumlah Donasi : {{ input_form.donasi }}<br><br>
				<input id="submit" type="submit" value="Submit">
			</form>
	    </div>

	</div>
<br>
	</section>

	<style type="text/css">
		input {
			padding: 5px 5px 5px 5px;
			border-radius: 10px;
			border-width: 1px;
			width: 100%;
			border-color: white;
		}
		.container {
			font-size: 15px;
			margin-bottom: 100px;

		}
		#submit {
			width: 30%;
			background-color: #34F6F2;
			color: white;
			font-weight: bold;
		}
		#submit:hover {
			width: 30%;
			
			background-color: #07A3D5;
			color: white;
			font-weight: bold;
		}
	</style>
	
{% endblock content %}

relawan/templates/main/relawan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Cov19 Relawan</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock meta %}

{% block content %}
 <!-- <h1>Hello, world!</h1>-->
  <div class="khusus">
  <div class="card" style="padding: 10px">
  	<p><a style="background: transparent; color: black" href="{% url 'relawan:relawan' %}">Relawan</a></p>

  </div>

<div class="card" style="margin-top: 30px !important">
	    	<div class="" style="margin-top: 20px !important"></div>
	    	<!--<input style="margin-left: 10px; width: 50%" id="keyword" placeholder="Search....">-->

	    	<div class="">
	    		<div class="khusus" style="text-align: right;margin-bottom: 20px;"><button type="button" class="btn btn-info btn-primary" id="tombol" >Tambah Relawan</button></div>
	    	<!--<table class="table" id="myTable">
	    		<button type="button" class="btn btn-primary"><a id="link" href="/formrelawan">Tambah Relawan</a></button>
	    		
	    		<thead >
	    		<tr>
	    			<th>Nama</th>
	    			<th>Alamat</th>
	    			<th>Donasi</th>
	    		</tr>
	    		</thead>
			{% if relawans %}
			<tbody>
				{% for relawan in relawans %}
		
				<tr>
					<td>{{ relawan.display_name }}</td>
					<td>{{ relawan.alamat }}</td>
					<td>{{ relawan.donasi }}</td>
						
				</tr>
				
		<br/>
		{% endfor %}
		</tbody>
	{% endif %}
</table>-->
<table class="table" id="myTable">
	<thead >
	    		<tr>
	    			<th>Nama</th>
	    			<th>Alamat</th>
	    			<th>Donasi</th>
	    		</tr>
	    		</thead>
	    		<tbody id="isi_data">
	    			<tr id="noData"><td  colspan="3" style="text-align: center;"><h3>No data</h3></td></tr>
	    		</tbody>
</table>
<div id='hmm'></div>
</div>

</div>

	     

  <!-- Modal -->
  <div id="bg">
  	
  </div>
  <div class="sesuatu" id="myModal" >
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="card modal-content" id="cards">
        <div class="modal-header">
          <button type="button" class="close" >&times;</button>
          <h4 class="modal-title">Silakan Masukan Data</h4>
        </div>
        <div class="modal-body">
        
			<form method="POST" id="form">
				{% csrf_token %}
				Nama<br> {{ input_form.display_name }}<br><br>
				Alamat<br> {{ input_form.alamat }}<br><br>
				Jumlah Donasi<br> {{ input_form.donasi }}<br><br>
				<input id="submit" type="submit" value="Submit">
			</form>
	    
        </div>
        <div class="modal-footer">
         <button type="button" class="btn btn-default" id="tombol-tutup">Close</button>
        </div>
      </div>
      
    </div>

  </div>

  
</div>


  
    <style type="text/css">
	div.khusus {
		margin-left: auto;
		margin-right: auto;
		width: 80%;
		font-size: 11px;
	}
	.card-body{
		margin-left: auto;
		margin-right: auto;
		width: 50%;
		text-align: center;
	}
	.row {
		margin-left: auto;
		margin-right: auto;
		width: 80%;
	}
	p {
		margin: 0px;
		font-size: 17px;
	}

	.pagination {
		position: inherit;
	}

	table {
		font-size: 12px;
	}
	button {
		border: none;
		padding: 10px 10px 10px 10px;
	}
	#link{
		color: white;
	}
	div{
		margin-left: none;
		margin-right: none;
		width: 100%;
		
	}
	input {
			padding: 5px 5px 5px 5px;
			border-radius: 10px;
			border-width: 1px;
			width: 100%;
			border-color: white;
		}
		#submit {
			width: 30%;
			background-color: rgba(2,0,36,1);
			color: white;
			font-weight: bold;
		}
		#submit:hover {
			width: 30%;
			
			background-color: #07A3D5;
			color: white;
			font-weight: bold;
		}
		label {
			display: none;
		}
		ul.pagination{
			background : transparent;
			box-shadow: none;
			margin-left: 100px; 
		}

		.sesuatu{
			display: none;
		}
		#bg{
		opacity:.80;
		position: absolute;
		display: none;
		position: fixed;
		top: 0%;
		left: 0%;
		width: 100%;
		height: 100%;
		background-color: #000;
		z-index:1001;
		opacity: 0.8;
		}
		#cards{
			z-index: 1005;
			background: linear-gradient(90deg, rgba(208,244,255,1) 0%, rgba(198,255,254,0.8127626050420168) 51%, rgba(0,202,255,0.2329306722689075) 100%);
			opacity: 1;
			position: fixed;
			bottom: 20%;
			width: 40%;
		}
		@media screen and (max-width: 1000px){
			#cards{
				width: 70%;
			}
		}


		


</style>
    <script type="text/javascript">
		$(document).ready(function(){
			$('#tombol').click(function(){
				$('#myModal, #bg').fadeIn("slow");
			});
			$('#tombol-tutup').click(function(){
				$('#myModal, #bg').fadeOut("slow");
			});
			$('.close').click(function(){
				$('#myModal, #bg').fadeOut("slow");
			});

		});
		$("#keyword").keyup(function() {
			var cari = $("#keyword").val();
			console.log(cari);
			console.log(cari.length);
		});
			
	</script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
		$(document).ready(function(){
			//alert('Saya dieksekusi');
			$.ajax({
				url : "/dataKasus",
				success: function(data){
					var array_items = data;
					console.log(array_items);
						for (i=0; i<array_items.length; i++) {
							nama = array_items[i].display_name;
							alamat = array_items[i].alamat;
							donasi = array_items[i].donasi;
							$("#isi_data").append("<tr><td>" + nama + "</td> " +
								"<td>" + alamat + "</td> " + "<td>" + donasi + "</td></tr> ");
							$("#noData").hide();
						}
					
			}
			})
		});
	</script>
	<script>
		const form = document.getElementById('form');
		form.addEventListener("submit", submitHandler);

		function submitHandler(e) {
			e.preventDefault();
			$.ajax({
            type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
            url         : "{% url 'relawan:saverelawan' %}", // the url where we want to POST
            data        : $('#form').serialize(), // our form data
            dataType    : 'json', // what type of data do we expect back from the server
            success     : successFunction
        });
		}
		function successFunction(msg) {
        if (msg.message === 'success') {
            alert('Berhasil menambahkan relawan!');
            form.reset()
        }
        {window.location.reload();}
    }
	</script>
{% endblock content %}