account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register', views.registerPage, name='register'),
    path('login', views.loginPage, name='login'),
    path('logout', views.logoutUser, name='logout'),
]

article/urls.py
from django.urls import path
from . import views

app_name = 'article'
# urls
urlpatterns = [
    path('article_list/', views.article_list, name='article_list'),
    path('article/<int:id>/', views.article_page, name='article_page'),
    path('add/', views.article_add, name='article_add'),
    path('artikel/<int:id>/delete/', views.article_delete, name='article_delete'),
    path('data_article', views.data_article, name='data_article'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('kasus', views.kasus),
]

ppwb01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('relawan.urls')),
    path('', include('article.urls')),
    path('', include('komentar.urls')),
    path('', include('account.urls')),
]

relawan/urls.py
from django.urls import re_path

from . import views

app_name = 'relawan'

urlpatterns = [
    re_path(r'^relawan', views.relawan, name='relawan'),
    re_path('formrelawan', views.formRelawan, name='formrelawan'),
    re_path('saverelawan', views.saverelawan, name='saverelawan'),
    re_path('dataKasus', views.dataKasus),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,900' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Cardo:100,200,300,400,500,600,700,900' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <link rel="stylesheet" href="{% static 'css/styleTK2.css' %}">

    <style type="text/css">
      body {
        font-size: 15px;
      }
      a {
        font-size: 15px;
      }
      .myPage {
        padding: 14px 16px;
      }

      .links {
        padding: 14px 16px;
        font-size: 15px;
      }
      #logout {
        color: red;
        font-weight: bold;
      }
      .glyphicon{
        margin-right: 5px; 
      }
    </style>
    
  {% block meta %}
  {% endblock meta %}
</head>

<body><!--
<nav>
	<ul id="myDIV">
  <li class="myPage">Cov19</li>
  <li class="links"><a class="bton" href="#kontak">Kontak</a></li>
  <li class="links"><a class="bton" href="#minat">Minat</a></li>
  <li class="links"><a class="bton" href="{% url 'article:article_list' %}" id="artikel">Artikel</a></li>
  <li class="links"><a class="bton" href="{% url 'relawan:relawan' %}">Relawan</a></li>
  <li class="links"><a class="bton" href="{% url 'main:home' %}">Beranda</a></li>
</ul>
</nav>-->

<nav class="navbar">
 <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" style="background-color: rgba(2,0,36,1)" data-toggle="collapse" data-target="#ahaha">
        <span style="background-color: white" class="sr-only">Toggle navigation</span>
        <span style="background-color: white" class="icon-bar"></span>
        <span style="background-color: white" class="icon-bar"></span>
        <span style="background-color: white" class="icon-bar"></span>
      </button>
    </div>
  <div class="collapse navbar-collapse" id="ahaha">
    <ul class="navbar-nav">
      <li class="myPage" style="margin-right: 100px; margin-left: 50px;">Cov19</li>
      {% if user.is_authenticated %}
      <li class="">
        <a class="" href="{% url 'main:home' %}">Beranda</a>
      </li>
      <li class="">
        <a class="" href="{% url 'relawan:relawan' %}">Relawan</a>
      </li>
      <li class="">
        <a class="" href="{% url 'article:article_list' %}" id="artikel">Artikel</a>
      </li>
      {% endif %}
      {% if user.is_authenticated %}
       <span><a  class="links" id="logout" href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a></span>
       <span class="links" style=""><span class="glyphicon glyphicon-user"></span>Hello, {{request.user}}</span>
       {% else %}
       <span><a  class="links" href="{% url 'account:login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a></span>
       <span><a  class="links" href="{% url 'account:register' %}"><span class="glyphicon glyphicon-user"></span>Signup {{author}}</a></span>
       {% endif %}
  
    </ul>
    
  </div>
</div>
  
   

  

</nav>
{% block content %}
  {% endblock content %}


<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>
</body>
  
</html>